apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::083079577498:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters

    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::083079577498:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-175SZUBE27LFT
      username: system:node:{{EC2PrivateDNSName}}
   
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-23T00:56:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "858"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2207443b-f45f-451d-a125-1019a3dff8ab
